apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: default
  source:
    repoURL: https://github.com/skywno/gitops-kyverno.git
    targetRevision: main
    path: apps/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        # Ignore securityContext mutations at pod level (Kyverno adds security contexts)
        - /spec/template/spec/securityContext
      jqPathExpressions:
        # Ignore image digest mutations for all containers (Kyverno replaces tag with digest)
        - .spec.template.spec.containers[]?.image
        # Ignore securityContext mutations for all containers
        - .spec.template.spec.containers[]?.securityContext
  dependsOn:
    - name: infra-configs